### ISSUE TITLE
Sans switch pour Alert.jsx

### ISSUE THREAD

**Issue by Zharkan** [raphaelsanchez/learn-nextjs#7]
Je ne peux pas créer de nouvelle branche alors je te propose ça dans l'issue, tu peux faire plus simple pour ton composant, plutôt qu'utiliser switch tu peux faire ça : 

```jsx
// Alert.jsx
import styles from './Alert.module.css'
import { clsx } from 'clsx'
import { AlertTriangle, CheckCircle, Info, XOctagon } from 'react-feather'

export default function Alert({ children, type }) {
  console.log('Alert : ', type)

  const icon = {
    info: <Info />,
    success: <CheckCircle />,
    warning: <AlertTriangle />,
    error: <XOctagon />,
  }

  return (
    <div
      className={clsx({
        [styles.success]: type === 'success',
        [styles.error]: type === 'error',
        [styles.info]: type === 'info',
        [styles.warning]: type === 'warning',
        [styles.container]: true,
      })}
    >
      {icon[type]}
      {children}
    </div>
  )
}
```

**Comment by raphaelsanchez** [comment]
@Zharkan Je t'avoue que j'ai du mal a comprendre comme on passe de ça :
![image](https://user-images.githubusercontent.com/6806913/213882002-632e169d-4382-4e92-b9e9-f6e600921fad.png)
qui es un objet, à ça :
![image](https://user-images.githubusercontent.com/6806913/213882026-60ca9e0f-f6b0-4aaa-b705-62758e710c96.png)
